// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWMpSZGUzpT5a6bsqVRYcorXm5k3KMOs',
    appId: '1:378454359271:android:a525fb0c1fd65510197642',
    messagingSenderId: '378454359271',
    projectId: 'edutrack-family',
    storageBucket: 'edutrack-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArzxjC6U2bEeveGliBWw4oeHamhhBhj-c',
    appId: '1:378454359271:ios:c12b3d92a0feda6c197642',
    messagingSenderId: '378454359271',
    projectId: 'edutrack-family',
    storageBucket: 'edutrack-family.firebasestorage.app',
    androidClientId: '378454359271-0atd6c73ge11crmn2ijlvslqnpuisfce.apps.googleusercontent.com',
    iosClientId: '378454359271-fkr425dse6mc95p27e522ot7i7td0lnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Zyn4UUaotY6V4JEpTTI6VYKcgikJGlc',
    appId: '1:378454359271:web:1af45c490fab2c0b197642',
    messagingSenderId: '378454359271',
    projectId: 'edutrack-family',
    authDomain: 'edutrack-family.firebaseapp.com',
    storageBucket: 'edutrack-family.firebasestorage.app',
    measurementId: 'G-LBNGSKFF8T',
  );
}
